# Generated by Django 4.0.3 on 2022-03-31 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_options_customuser_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joindre',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
